package GUI;


import API.PriceUpdater;
import Controllers.UserController;
import Domain.Card;
import Utils.MisMetodos;
import java.awt.Frame;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Carlos
 */
public class CardDetailDialog extends javax.swing.JDialog {

    /**
     * Creates new form CardDetailDialog2
     */
    private final Card card;
    
    public CardDetailDialog(Frame parent, Card card) {
        super(parent, "Detalles de la carta", true);
        this.card = card;
        initComponents();
        updatePriceLabel.setVisible(false);
        setLocationRelativeTo(parent);
        loadCardDetails(card);
    }
    
    public void loadCardDetails(Card card){
        
        cantjLabel.setText(String.valueOf(getUserCardCount()));
        loadImage(card.getImageUrl());
        nombre.setText(card.getName());
        rareza.setText(card.getRarity());
        numColeccionista.setText(card.getCollector_number());
        edicion.setText(card.getSet_name());
        idioma.setText(card.getLang());
        valorLabel.setText(card.getEurPrice());
        valorFoilLabel.setText(card.getEurPriceFoil());
    }
    
    // Método para cargar la imagen de la carta a través de la url
    public void loadImage(String urlImage){
        try {
            URL url = new URL(card.getImageUrl()); // método personalizado que devuelve la URL
            ImageIcon icon = new ImageIcon(url);
            Image scaled = icon.getImage().getScaledInstance(223, 310, Image.SCALE_SMOOTH); // ajusta tamaño
            imageLabel.setIcon(new ImageIcon(scaled));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Método para contar las copias que tiene el USR de una misma carta
    public int getUserCardCount(){
        Card userCard = UserController.cardMap.get(card.getCardId());
        
        // Si el userMap contiene la carta
        if(userCard != null){
            return userCard.getCardCount();
        }
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreJLabel1 = new javax.swing.JLabel();
        rarezajLabel2 = new javax.swing.JLabel();
        numColjLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idiomajLabel2 = new javax.swing.JLabel();
        valorjLabel2 = new javax.swing.JLabel();
        valorFoiljLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        rareza = new javax.swing.JLabel();
        numColeccionista = new javax.swing.JLabel();
        edicion = new javax.swing.JLabel();
        idioma = new javax.swing.JLabel();
        valorLabel = new javax.swing.JLabel();
        valorFoilLabel = new javax.swing.JLabel();
        linkButton = new javax.swing.JButton();
        updatePriceButton = new javax.swing.JButton();
        addCardButton = new javax.swing.JButton();
        cerrarButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();
        cantjLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        updatePriceLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nombreJLabel1.setText("Nombre:");

        rarezajLabel2.setText("Rareza:");

        numColjLabel3.setText("Num.Col.");

        jLabel1.setText("Edición:");

        idiomajLabel2.setText("Idioma:");

        valorjLabel2.setText("Valor:");

        valorFoiljLabel3.setText("FOIL:");

        nombre.setText("jLabel2");

        rareza.setText("jLabel2");

        numColeccionista.setText("jLabel2");

        edicion.setText("jLabel2");

        idioma.setText("idioma");

        valorLabel.setText("jLabel3");

        valorFoilLabel.setText("jLabel2");

        linkButton.setText("Link");
        linkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkButtonActionPerformed(evt);
            }
        });

        updatePriceButton.setText("Actualizar Precio");
        updatePriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePriceButtonActionPerformed(evt);
            }
        });

        addCardButton.setText("Añadir ");
        addCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCardButtonActionPerformed(evt);
            }
        });

        cerrarButton.setText("CERRAR");
        cerrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Quitar");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        cantjLabel.setText("jLabel2");

        jLabel3.setText("My Deck:");

        updatePriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatePriceLabel.setText("jLabel2");
        updatePriceLabel.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cerrarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(updatePriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rarezajLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(idiomajLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valorFoiljLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valorjLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nombreJLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numColjLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rareza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numColeccionista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(edicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(idioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valorFoilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(addCardButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(updatePriceButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(linkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantjLabel)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreJLabel1)
                            .addComponent(nombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rarezajLabel2)
                            .addComponent(rareza))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numColjLabel3)
                            .addComponent(numColeccionista))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(edicion))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idiomajLabel2)
                            .addComponent(idioma))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valorjLabel2)
                            .addComponent(valorLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valorFoiljLabel3)
                            .addComponent(valorFoilLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updatePriceButton)
                            .addComponent(linkButton)))
                    .addComponent(imageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addCardButton)
                        .addComponent(removeButton))
                    .addComponent(updatePriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(cerrarButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarButtonActionPerformed
     dispose();
    }//GEN-LAST:event_cerrarButtonActionPerformed

    // Método para abrir el link de la carta
    private void linkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkButtonActionPerformed
        String link = card.getNewUrl();
        // Abrir la URL si no es nula
        if (link != null && !link.isEmpty()) {
            MisMetodos.abrirURL(link);
        } else {
            JOptionPane.showMessageDialog(this, "La URL de CardMarket no está disponible.", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_linkButtonActionPerformed
    // Añadir carta al JSON del USR
    private void addCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCardButtonActionPerformed
        UserController.addCardToMap(card);
        // Actualiza la etiqueta que muestra el total de cartas
        cantjLabel.setText(String.valueOf(getUserCardCount()));
    }//GEN-LAST:event_addCardButtonActionPerformed

    // Quitar carta del JSON del USR
    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        UserController.removeCardFromMap(card);
        // Actualiza la etiqueta que muestra el total de cartas
        cantjLabel.setText(String.valueOf(getUserCardCount()));
    }//GEN-LAST:event_removeButtonActionPerformed

    private void updatePriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePriceButtonActionPerformed
        updatePriceLabel.setText("ACTUALIZANDO PRECIO...");
        updatePriceLabel.setVisible(true);

        SwingWorker<Void, Void> worker = new SwingWorker<>() {
            @Override
            protected Void doInBackground() {
                PriceUpdater.updateCardPrice(card);
                return null;
            }

            @Override
            protected void done() {
                valorLabel.setText(card.getEurPrice());
                valorFoilLabel.setText(card.getEurPriceFoil());
                updatePriceLabel.setText("PRECIOS ACTUALIZADOS");

                // Opcional: ocultar después de unos segundos
                Timer timer = new Timer(2000, e -> updatePriceLabel.setVisible(false));
                timer.setRepeats(false);
                timer.start();
            }
        };

        worker.execute();
    }//GEN-LAST:event_updatePriceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardDetailDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCardButton;
    private javax.swing.JLabel cantjLabel;
    private javax.swing.JButton cerrarButton;
    private javax.swing.JLabel edicion;
    private javax.swing.JLabel idioma;
    private javax.swing.JLabel idiomajLabel2;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton linkButton;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombreJLabel1;
    private javax.swing.JLabel numColeccionista;
    private javax.swing.JLabel numColjLabel3;
    private javax.swing.JLabel rareza;
    private javax.swing.JLabel rarezajLabel2;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton updatePriceButton;
    private javax.swing.JLabel updatePriceLabel;
    private javax.swing.JLabel valorFoilLabel;
    private javax.swing.JLabel valorFoiljLabel3;
    private javax.swing.JLabel valorLabel;
    private javax.swing.JLabel valorjLabel2;
    // End of variables declaration//GEN-END:variables
}
